### PR TITLE
Ayo

### PR DESCRIPTION
**Pull request by ethanlchristensen**

### CODE REVIEW

**Comment by nulzo** [comment]
@ethanlchristensen is this mostly formatting changes?

**Comment by ethanlchristensen** [comment]
@nulzo perhaps

**Comment by nulzo** [comment]
Most descriptive PR ever made

**Comment by ethanlchristensen** [comment]
@nulzo linter, black, moved capturing of STDOUT for bruhpy and nolang to separate util file

**Review by nulzo — APPROVED** [review]
YUP

**Pull request merged**
