### PR TITLE
Bsllc development

### PR DESCRIPTION
**Pull request by ethanlchristensen**
[tip hat]

### CODE REVIEW

**Review by nulzo — COMMENTED** [review]
you must have me messed up if you think I'm approving this PR!

**Comment by ethanlchristensen** [comment]
@nulzo please kindly explain any issues you see with the code! 😎

**Comment by nulzo** [comment]
@ethanlchristensen contains.py line 16

**Comment by ethanlchristensen** [comment]
@nulzo changes have been made. Please kindly review, and merge is applicable! 😄

**Review by nulzo — APPROVED** [review]
gg.

**Pull request merged**
