### PR TITLE
Added ghost ping method with a static variable that can easily modify…

### PR DESCRIPTION
**Pull request by nulzo**
… who gets "ghost pinged". Ghost pinging occurs at a random interval of [3 min, 3 hr].

### CODE REVIEW

**Comment by ethanlchristensen** [comment]
@nulzo Would you be able to change the areas where you hard coded in the guild id ~ this is passed in with the script file and is made available in the Config.py.

That is
```py
import Config
GUILD                   = Config.GUILD
 . . . 
channel: discord.TextChannel = random.choice(self.get_guild(GUILD).text_channels)
```

**Comment by nulzo** [comment]
@ethanlchristensen Sure, didn't catch that. 
Likewise, you'll note the hardcoded statement below has been rectified.
```python 
msg: discord.Message = await channel.send('<@id>')
```

**Comment by Mr-Oregano** [comment]
I have rectified deeznuts inside of your nostrils

**Comment by ethanlchristensen** [comment]
@nulzo  This is epic! I was going to say the same about the USER ID and to mask it and to pass it in through the script, but I suppose that isn't as important as the TOKEN and GUILD ! God Speed!

**Review by ethanlchristensen — APPROVED** [review]

**Pull request merged**
