### PR TITLE
Project reorganization

### PR DESCRIPTION
**Pull request by Mr-Oregano**
Overview of Changes:
 - Can remove `run.bat`/`run.sh` since `run.py` now to loads env variables from a `.env` file
 - Merged `class FortniteClient` and `class FortniteBallsBot`
 - `slash_master.py` was moved outside of the `_slash/`
 - `slash_master.py` uses generator to iterate valid python command modules
 - Added `requirements.txt` file to keep track of required python modules

### CODE REVIEW

**Comment by nulzo** [comment]
Nope.

**Comment by Mr-Oregano** [comment]
> Nope.

ermmmmm... yes

**Comment by nulzo** [comment]
erm ..

**Review by nulzo — APPROVED** [review]
bro really said 🤓

**Pull request merged**
